version: "3.1"

services:
  backend:
    build:
      context: ./django_djoser_custom_user
      dockerfile: Dockerfile
    image: backend-image:v1
    environment:
      - PORT=8000
    env_file:
      - parquecar_backend2/backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./media_files:/app/media
      - ./static:/app/static
